import Model, { attr } from '@ember-data/model';

import {
  MANDAAT_AANGEWEZEN_BURGEMEESTER_CODE,
  MANDAAT_BURGEMEESTER_CODE,
  MANDAAT_DISTRICT_BURGEMEESTER_CODE,
  MANDAAT_DISTRICT_SCHEPEN_CODE,
  MANDAAT_GEDEPUTEERDE_CODE,
  MANDAAT_GEMEENTERAADSLID_CODE,
  MANDAAT_LID_RMW_CODE,
  MANDAAT_LID_VAST_BUREAU_CODE,
  MANDAAT_SCHEPEN_CODE,
  MANDAAT_TOEGEVOEGDE_SCHEPEN_CODE,
  MANDAAT_VOORZITTER_BCSD_CODE,
  MANDAAT_VOORZITTER_GEMEENTERAAD_CODE,
  MANDAAT_VOORZITTER_RMW_CODE,
  MANDAAT_VOORZITTER_VAST_BUREAU_CODE,
} from 'frontend-lmb/utils/well-known-uris';

export default class BestuursfunctieCodeModel extends Model {
  @attr uri;
  @attr label;

  get rankForSorting() {
    const mandateRankForSorting = {
      [MANDAAT_GEDEPUTEERDE_CODE]: 13,
      [MANDAAT_DISTRICT_BURGEMEESTER_CODE]: 12,
      [MANDAAT_BURGEMEESTER_CODE]: 11,
      [MANDAAT_AANGEWEZEN_BURGEMEESTER_CODE]: 10,
      [MANDAAT_DISTRICT_SCHEPEN_CODE]: 9,
      [MANDAAT_SCHEPEN_CODE]: 8,
      [MANDAAT_TOEGEVOEGDE_SCHEPEN_CODE]: 8,
      [MANDAAT_VOORZITTER_VAST_BUREAU_CODE]: 7,
      [MANDAAT_LID_VAST_BUREAU_CODE]: 6,
      [MANDAAT_VOORZITTER_GEMEENTERAAD_CODE]: 5,
      [MANDAAT_GEMEENTERAADSLID_CODE]: 4,
      [MANDAAT_VOORZITTER_BCSD_CODE]: 3,
      [MANDAAT_VOORZITTER_RMW_CODE]: 2,
      [MANDAAT_LID_RMW_CODE]: 1,
    };
    return mandateRankForSorting[this.uri] || 0;
  }

  get isBurgemeester() {
    return (
      this.uri === MANDAAT_BURGEMEESTER_CODE ||
      this.uri === MANDAAT_AANGEWEZEN_BURGEMEESTER_CODE ||
      this.uri === MANDAAT_DISTRICT_BURGEMEESTER_CODE
    );
  }
}
